### ISSUE TITLE
Make sure all pages have <title> and other meta-things in <head>

### ISSUE THREAD

**Issue by MichaelAllenWarner** [utkwdn/utk-atlas#123]
All pages should have at least the following in the `<head>` (using Next.js's `<Head>` component, perhaps at the layout-level?):

- `<meta charSet="utf-8" />`
- `<meta name="viewport" content="initial-scale=1.0, width=device-width" />`
- An appropriate (page-specific) `<title>` tag
- An appropriate (page-specific) `<meta name="description" content="..." />` tag
- A favicon `<link>`

(some of these might already be present on all or some pages)

**Comment by pikemurdy** [comment]
On this, we also use the YoastSEO plugin. And with Yoast you can edit meta info, add opengraph sharing stuff, etc. We'll need to make sure the <head> pulls from that. WPengine has told us it's not hard.

**Comment by naylormar** [comment]
All the pages with wordpress content should pull from Yoast now. For special pages like alpha that don't exist in wordpress, we'll need to manually add head info on the Atlas side.

**Comment by pikemurdy** [comment]
I added a meta description (using Yeast) to this page, but I don't see it appearing in the <head>. Are we sure Yoast is hooked up? @naylormar ?

https://dev.cms.utk.edu/academics

**Comment by naylormar** [comment]
![Screenshot 2022-12-02 at 4 30 58 PM](https://user-images.githubusercontent.com/4965463/205396651-273e2bba-869f-44b4-886f-951caa4faf81.png)
I'm seeing a meta description. Does this look right? It might be that it was slow to update.
