### ISSUE TITLE
Mobile Menu Stickiness

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utk-atlas#166]
On mobile, when you open the main menu, and select a page it'll take you to that page and close the menu. If you open it again, you can tap different pages and the menu does not close. If you manually close it (tapping the X), you'll see that you have indeed navigated to the new page, but the menu had stayed open.

https://user-images.githubusercontent.com/7902085/205991958-df4e2110-eeea-460e-a3b5-028d180c4962.MP4

**Comment by MichaelAllenWarner** [comment]
@pikemurdy 

Handing back to you for review (though at the moment it can only be tested in local development because there's a little error that's blocking the build on `development`; Mark knows about it and will fix it later).
