### ISSUE TITLE
Homepage Video on iOS

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utk-atlas#214]
In iOS if you visit the homepage, and then an interior page, and then the homepage again, the 'textural video' of the two graduates takes over the screen.

https://user-images.githubusercontent.com/7902085/207060234-71b26cf3-8c9e-4fa0-8bad-6c18c946888f.mov

**Comment by MichaelAllenWarner** [comment]
@pikemurdy

First thing we should try is adding the [`playsinline`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-playsinline) attribute to the `<video>` element. Should be done on the WordPress side if possible, so assigning back to you for now, but as a last resort I can do it on the Next.js side if absolutely necessary.

**Comment by pikemurdy** [comment]
That fixed it, it looks like.
