### ISSUE TITLE
Main logo is maybe too small at some screen-widths (mobile, and 992px-breakpoint)

### ISSUE THREAD

**Issue by MichaelAllenWarner** [utkwdn/utk-atlas#41]
We could probably increase the logo's size where needed without having to make anything else smaller, though at the 992-breakpoint it might be better to increase the logo's size more substantially, which _would_ require either decreasing the size of the main-nav or altering the layout in some way.

Here is 320px (the narrowest viewport I typically consider):

![Screen Shot 2022-07-08 at 9 47 04 AM](https://user-images.githubusercontent.com/44578578/178004579-33cd55dc-2bb6-42d1-a715-26b4d8f25d7f.png)

And here is the 992px breakpoint:

![Screen Shot 2022-07-08 at 9 48 06 AM](https://user-images.githubusercontent.com/44578578/178004792-181bc187-9f3a-44b0-b63a-6edc5ca2cf71.png)

**Comment by pikemurdy** [comment]
Yes. At the smaller sizes, it should convert to simply showing the power-t block (dropping the words).

Also, the logo is currently too large at the widest viewports.
