### ISSUE TITLE
Refactor site to use the Framework more directly

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utk-atlas#46]
Currently, the site pulls in the beta version of the Framework. To change styles in atlas, you must change the framework (and go through the update process). Should the frame work just be forked, and integrated more directly in atlas so that we're not 'overwriting' the CSS to make style changes.

Is there a way to improve development efficiency?

**Comment by spworky** [comment]
#Framework Integrated #67 

@pikemurdy utksds-framework dependency has been removed and framework is now integrated locally in project.
scss --> framework --> components, regions, styles, _custom_variables.scss
