### ISSUE TITLE
Secondary navigation

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utk-atlas#56]
The main menu of the site is built in wordpress: https://content.cms.utk.edu/wp-admin/nav-menus.php

The secondary menu is not displaying, though. You can see examples of how it should work here:
https://volsonline.utk.edu/online-learning/about-us/

Or here:
https://www.utsi.edu/academics/

**Comment by MichaelAllenWarner** [comment]
I believe I fixed this while getting the build working: https://dev.cms.utk.edu/about/numbers
